# Generated by Django 4.2.26 on 2025-11-18 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="activesession",
            name="expiry_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
